USE [SuperStoreDW]
GO

/****** Object:  Table [dbo].[DimShipMode]    Script Date: 7/11/2026 10:51:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimShipMode](
	[ShipModeSK] [int] IDENTITY(1,1) NOT NULL,
	[Ship Mode] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ShipModeSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


